version: '3.8'

services:
  pg:
    image: postgres:14.3-alpine
    container_name: pg
    restart: always
    env_file: .env
    environment: 
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASS}
        POSTGRES_DB: ${PG_NAME}
        POSTGRES_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PG_USER}@takehome.com
        PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports: 
        - "5001:80"
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    image: client:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
  mcs:
    container_name: mcs
    build:
      context: mcs
      dockerfile: Dockerfile
    image: mcs:latest
    ports:
      - "8081:8081"
    expose:
      - "8081"
  satellite:
    container_name: satellite
    build:
      context: satellite
      dockerfile: Dockerfile
    image: satellite:latest
    ports:
      - "8082:8082"
    expose:
      - "8082"